name: restotag_customer_app
description: "Customer App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.7.2
  shared_preferences: ^2.5.3
#  qr_code_scanner: ^1.0.1

  # Helper
  intl: ^0.20.2

  # UI
  flutter_otp_text_field: ^1.5.1+1

  # Firebase
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/branding/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/resto_tag.jpg

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/branding/resto_tag.png
  android_12:
    image: assets/branding/resto_tag.png
    icon_background_color: "#FFFFFF"
