// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5HrgEm8LUSQtgu5tTjOxJttm3UU4byUE',
    appId: '1:375989348454:web:6f44df3e85150a4a5c25a7',
    messagingSenderId: '375989348454',
    projectId: 'restotag',
    authDomain: 'restotag.firebaseapp.com',
    storageBucket: 'restotag.firebasestorage.app',
    measurementId: 'G-Z7BVLD978E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf8e2cIJchz5NtzH8EMtkUCKin6t8XvLE',
    appId: '1:375989348454:android:cbaadcd7f99730095c25a7',
    messagingSenderId: '375989348454',
    projectId: 'restotag',
    storageBucket: 'restotag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLccnjLo6a48Pey7sfBFj7WHxZAPGcxFk',
    appId: '1:375989348454:ios:950d7efd1dc4a9e75c25a7',
    messagingSenderId: '375989348454',
    projectId: 'restotag',
    storageBucket: 'restotag.firebasestorage.app',
    iosBundleId: 'com.restotag.customer.restotagCustomerApp',
  );
}
